version: v1

endpoints:
  - name: acr
    type: acr
    path: /events/acr
  - name: distribution
    type: distribution
    path: /events/distribution
  - name: dockerhub
    type: dockerhub
    path: /events/dockerhub
  - name: generic
    type: generic
    path: /events/generic

repositories:
  - name: kobold-test
    url: http://gitea.local:3000/kobold/kobold-test.git
    username: ${GITEA_USER}
    password: ${GITEA_PASS}

subscriptions:
  - name: e2e
    endpointRefs:
      - name: acr
      - name: dockerhub
      - name: distribution
      - name: generic
    repositoryRef:
      name: kobold-test
    branch: main
    strategy: commit
    scopes: []
